services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    ports:
      - "8000:8000"

  db:
    image: postgres:17

    environment:
      POSTGRES_USER: sara
      POSTGRES_PASSWORD: motdepasse123
      POSTGRES_DB: devopsdb

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
